environments:
  dev:
    pipelines:
      - GocdPlayground_YAML_Plugin

pipelines:
  GocdPlayground_YAML_Plugin:
    group: playground
    materials:
      git:
        git: https://github.com/ajitsing/GocdPlayground.git
        branch: master
    stages:
      - demo:
          jobs:
            run:
              artifacts:
                - build:
                    source: ./*
                    destination: source_code
              tasks:
                - exec:
                    command: bash
                    arguments:
                     - -c
                     - sh hello.sh
